[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${KDE4_BIN_INSTALL_DIR}/startkde
TryExec=${KDE4_BIN_INSTALL_DIR}/startkde
Name=KDE Plasma Workspace
Name[ca]=Espai de treball del Plasma del KDE
Name[fi]=KDE Plasma-työtila
Name[fr]=Espace de travail de Plasma de KDE
Name[he]=סביבת עבודה של KDE Plasma
Name[ia]=Spatio de labor de Plasma de KDE
Name[kk]=KDE Plasma жұмыс орны
Name[km]=តំបន់​ការងារ​ផ្ទៃតុ​របស់​ប្លាស្មា​
Name[lt]=KDE Plasma darbastalio erdvė
Name[nb]=KDE Plasma arbeidsflate
Name[nl]=KDE Plasma-werkruimte
Name[pa]=KDE ਪਲਾਜ਼ਮਾ ਵਰਕਸਪੇਸ
Name[pl]=Przestrzeń robocza KDE
Name[pt]=Área de Trabalho Plasma do KDE
Name[pt_BR]=Espaço de trabalho Plasma do KDE
Name[ro]=Spațiu de lucru Plasma KDE
Name[sv]=KDE Plasma arbetsyta
Name[uk]=Робочий простір Плазми KDE
Name[x-test]=xxKDE Plasma Workspacexx
Comment=The desktop made by KDE
Comment[ca]=L'escriptori creat pel KDE
Comment[fi]=KDE:n tekemä työpöytä
Comment[fr]=Le bureau réalisé par KDE
Comment[he]=שולחן העבודה של KDE
Comment[hr]=Radna površina koju je napravio KDE
Comment[ia]=Le scriptorio facite per KDE
Comment[kk]=KDE үстелі
Comment[km]=ផ្ទៃ​តុ​បាន​បង្កើត​ដោយ​ KDE
Comment[lt]=Darbastalis sukurtas su KDE
Comment[nb]=Skrivebordet som KDE laget
Comment[nl]=Het bureaublad gemaakt door KDE
Comment[pl]=Pulpit KDE
Comment[pt]=O ambiente de trabalho feito pelo KDE
Comment[pt_BR]=O ambiente de trabalho feito pelo KDE
Comment[ro]=Biroul creat de KDE
Comment[sv]=Skrivbordet skapat av KDE
Comment[uk]=Стільниця, створена командою KDE
Comment[x-test]=xxThe desktop made by KDExx
