[Desktop Entry]
Encoding=UTF-8
Type=XSession
Exec=${KDE4_BIN_INSTALL_DIR}/startkde --failsafe
TryExec=${KDE4_BIN_INSTALL_DIR}/startkde
Name=KDE Plasma Workspace (failsafe session)
Name[he]=סביבת עבודה של KDE Plasma (הפעלה בטוחה)
Name[hr]=KDE Plasma Workspace (sigurnosna sesija)
Name[ia]=Spatio de labor de plasma de KDE (session con securitate)
Name[kk]=KDE Plasma жұмыс орны (қауіпсіз сеанс)
Name[nb]=KDE Plasma arbeidsflate (sikker økt)
Name[nl]=KDE Plasma-werkruimte (sessie met veilig mislukken)
Name[pa]=KDE ਪਲਾਜ਼ਮਾ ਵਰਕਸਪੇਸ (ਫੇਲ੍ਹ ਸੇਫ਼ ਸ਼ੈਸ਼ਨ)
Name[pt]=Área de Trabalho Plasma do KDE (sessão de recurso)
Name[pt_BR]=Espaço de trabalho Plasma do KDE (sessão a prova de falhas)
Name[ro]=Spațiu de lucru Plasma KDE (sesiune robustă)
Name[sv]=KDE Plasma arbetsyta (felsäker session)
Name[uk]=Робочий простір Плазми KDE (безпечний сеанс)
Name[x-test]=xxKDE Plasma Workspace (failsafe session)xx
Comment=The desktop made by KDE (failsafe session)
Comment[he]=שולחן העבודה של KDE (הפעלה בטוחה)
Comment[hr]=Radna površina koju je napravio KDE (sigurnosna sesija)
Comment[ia]=Le scriptorio facite per KDE (session con securitate)
Comment[kk]=KDE үстелі (қаупсіз сеанс)
Comment[nb]=Skrivebordet som KDE laget (sikker økt)
Comment[nl]=Het bureaublad gemaakt door KDE (sessie met veilig mislukken)
Comment[pa]=KDE ਵਲੋਂ ਬਣਾਇਆ ਡੈਸਕਟਾਪ (ਫੇਲ੍ਹਸੇਫ਼ ਸ਼ੈਸ਼ਨ)
Comment[pt]=O ambiente de trabalho feito pelo KDE (sessão de recurso)
Comment[pt_BR]=O ambiente de trabalho feito pelo KDE (sessão a prova de falhas)
Comment[ro]=Biroul creat de KDE (sesiune robustă)
Comment[sv]=Skrivbordet skapat av KDE (felsäker session)
Comment[uk]=Стільниця, створена командою KDE (безпечний сеанс)
Comment[x-test]=xxThe desktop made by KDE (failsafe session)xx
